# Generated by Django 3.2.12 on 2025-03-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_foodcategory_menuitem_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('room', 'Room'), ('package', 'Package'), ('venue', 'Venue')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('bookings_count', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupancy_rate', models.FloatField()),
                ('weather_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('special_event', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('date', 'category', 'item_id')},
            },
        ),
    ]
